### PR TITLE
Fixing Bug: inconsistent date formatting in feed listing

### LINKED ISSUE #39: Bug: inconsistent date formatting in feed listing
When a transaction timestamp is a whole number of seconds, the fraction component is not displayed causing the columns to misalign in the feed listings. this issue is largely present for internal transactions, but there is no obvious reason why this would be limited to the timestamps for internal transactions.

*Current behaviour:*
```plain
004 2018-07-03 12:47:02.883 +0000 UTC   16.00      MASTER_CARD...
005 2018-07-02 00:04:49 +0000 UTC       50.00      FASTER_PAYMENTS_IN...
```

*Desired behaviour:*
```plain
004 2018-07-03 12:47:02.883 +0000 UTC   16.00      MASTER_CARD...
005 2018-07-02 00:04:49.000 +0000 UTC   50.00      FASTER_PAYMENTS_IN...
```

### PR DESCRIPTION
**Pull request by alimasyhur**
# Fixes #39 

Fixes Bug inconsistent date formatting in feed listing.

I added default time format, and let the time format in feed listing follows it

### CODE REVIEW

File: cmd/listFeed.go [hunk 1]
```diff
@@ -16,6 +16,8 @@ var listFeedCmd = &cobra.Command{
 	Run:   listFeed,
 }
 
+var defaultTimeFormat = "2006-01-02 15:04:05.000 +0000 MST"
```
Comment (billglover) [inline cmd/listFeed.go]: As this line defines a package level variable, it's easy to miss given that it is in the `cmd/listFeed.go` file. Ideally this would be passed as a configuration parameter but doing so is outside the scope of this fix. A compromise would be to move this line to `cmd/root.go` so at least it is co-located with other configuration items.

**Review by billglover — CHANGES_REQUESTED** [review]
I've tested this PR and all looks good, many thanks. I've left one comment on the location of the package level variable. If you can address this, we should be good to merge.

File: cmd/listFeed.go (hunk 1 above)
Comment (alimasyhur) [reply cmd/listFeed.go]: sure, I moved it to root.go file

**Review by alimasyhur — COMMENTED** [review]
sure, I moved defaultTimeFormat to root.go file

**Review by billglover — APPROVED** [review]
Changes look good. Many thanks.
